
  CREATE TABLE "QLDKTS_17_02_2020"."GS_DM_LOAI_TAI_SAN" 
   (	"MA" VARCHAR2(255 BYTE), 
	"TEN" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"LOAI_HINH_TAI_SAN_ID" NUMBER, 
	"HM_THOI_HAN_SU_DUNG" NUMBER, 
	"HM_TY_LE" NUMBER, 
	"KH_THOI_HAN_SU_DUNG" NUMBER, 
	"KH_TY_LE" NUMBER, 
	"MO_TA" VARCHAR2(500 CHAR), 
	"CHE_DO_HAO_MON_ID" NUMBER, 
	"PARENT_ID" NUMBER, 
	"TREE_NODE" VARCHAR2(255 BYTE), 
	"TREE_LEVEL" NUMBER, 
	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 556 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DON_VI_TINH" VARCHAR2(255 BYTE), 
	"SO_THU_TU" NUMBER(18,0), 
	 CONSTRAINT "GS_DM_LOAI_TAI_SAN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "QLDKTS_TBS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "QLDKTS_TBS" ;
