
  CREATE TABLE "QLDKTS_17_02_2020"."GS_TEMP_DONG_BO_DU_LIEU" 
   (	"MA_TAI_SAN" VARCHAR2(48 BYTE) NOT NULL ENABLE, 
	"MA_LOAI_TAI_SAN" VARCHAR2(8 BYTE), 
	"MA_DON_VI" VARCHAR2(48 BYTE), 
	"TRANG_THAI" NUMBER, 
	"TEN_TAI_SAN" VARCHAR2(4000 BYTE), 
	"NGAY_DUYET" DATE DEFAULT SYSDATE, 
	"LOAI_HINH_TAI_SAN_ID" NUMBER, 
	"DU_AN_JSON" CLOB, 
	"QUYET_DINH_SO" VARCHAR2(25 BYTE), 
	"QUYET_DINH_NGAY" DATE, 
	"NUOC_SAN_XUAT_MA" VARCHAR2(25 BYTE), 
	"LY_DO_BIEN_DONG_MA" VARCHAR2(25 BYTE), 
	"NAM_SAN_XUAT" NUMBER, 
	"NGAY_NHAP" DATE, 
	"NGAY_SU_DUNG" DATE, 
	"GHI_CHU" VARCHAR2(500 BYTE), 
	"DON_VI_BO_PHAN_MA" VARCHAR2(25 BYTE), 
	"IS_TAI_SAN_TOAN_DAN" NUMBER(1,0) DEFAULT 0, 
	"CHUNG_TU_SO" VARCHAR2(255 BYTE), 
	"CHUNG_TU_NGAY" DATE, 
	"NGUYEN_GIA_BAN_DAU" NUMBER, 
	"GIA_MUA_TIEP_NHAN" NUMBER, 
	"LST_BIEN_DONG_JSON" CLOB, 
	"LST_HIEN_TRANG_JSON" CLOB, 
	"LST_NGUON_VON_JSON" CLOB, 
	"TAI_SAN_JSON" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QLDKTS_TBS" 
 LOB ("DU_AN_JSON") STORE AS SECUREFILE (
  TABLESPACE "QLDKTS_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("LST_BIEN_DONG_JSON") STORE AS SECUREFILE (
  TABLESPACE "QLDKTS_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("LST_HIEN_TRANG_JSON") STORE AS SECUREFILE (
  TABLESPACE "QLDKTS_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("LST_NGUON_VON_JSON") STORE AS SECUREFILE (
  TABLESPACE "QLDKTS_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("TAI_SAN_JSON") STORE AS SECUREFILE (
  TABLESPACE "QLDKTS_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
