INSERT INTO KT_TAISAN_31122014
SELECT DM_DONVI.MA_DON_VI,
DM_DONVI.TEN_DON_VI,
BD.MA_TAI_SAN,
(CASE SUBSTR(TS.MA_LOAI_TAI_SAN,0,1)
       WHEN '1' THEN  FN_LAY_TEN_TAI_SAN(BD.MA_TAI_SAN)
       ELSE TS.TEN_TAI_SAN
END ) TEN_TAI_SAN,
BD.DIEN_TICH,
BD.SO_LUONG,
BD.NGUYEN_GIA_NS,
BD.NGUYEN_GIA_KHAC,
BD.NGUYEN_GIA_ODA,
BD.NGUYEN_GIA_VIEN_TRO,
( CASE SUBSTR(TS.MA_LOAI_TAI_SAN,0,1)
         WHEN '1' THEN  BD.NGUYEN_GIA_NS
         WHEN '2' THEN FN_TINH_GTCL_HM_KH_MOI(BD.MA_TAI_SAN,TO_DATE('31/12/2014','DD/MM/YYYY') ,1,0,TS.CHE_DO_HACH_TOAN)
         WHEN '3' THEN FN_TINH_GTCL_HM_KH_MOI(BD.MA_TAI_SAN,TO_DATE('31/12/2014','DD/MM/YYYY') ,2,0,TS.CHE_DO_HACH_TOAN)
         WHEN '4' THEN FN_TINH_GTCL_HM_KH_MOI(BD.MA_TAI_SAN,TO_DATE('31/12/2014','DD/MM/YYYY') ,3,0,TS.CHE_DO_HACH_TOAN)
         ELSE FN_TINH_GTCL_HM_KH_MOI(BD.MA_TAI_SAN,TO_DATE('31/12/2014','DD/MM/YYYY') ,4,0,TS.CHE_DO_HACH_TOAN)
END ) GIA_TRI_CON_LAI,
(CASE WHEN NVL(BD.DIEN_TICH,0) < NVL(LAM_TRU_SO_NN,0)    THEN NVL(BD.DIEN_TICH,0) ELSE LAM_TRU_SO_NN END) LAM_TRU_SO_NN,
(CASE WHEN NVL(BD.DIEN_TICH,0) < NVL(HD_SN,0)    THEN NVL(BD.DIEN_TICH,0) ELSE HD_SN END) HD_SN,
(CASE WHEN NVL(BD.DIEN_TICH,0) < NVL(SX_KDDV,0)    THEN NVL(BD.DIEN_TICH,0) ELSE SX_KDDV END) SX_KDDV,
(CASE WHEN NVL(BD.DIEN_TICH,0) < NVL(CHO_THUE,0)    THEN NVL(BD.DIEN_TICH,0) ELSE CHO_THUE END) CHO_THUE,
(CASE WHEN NVL(BD.DIEN_TICH,0) < NVL(SX_KDDV_SAIPHEP,0)    THEN NVL(BD.DIEN_TICH,0) ELSE SX_KDDV_SAIPHEP END) SX_KDDV_SAIPHEP,
(CASE WHEN NVL(BD.DIEN_TICH,0) < NVL(DE_O,0)    THEN NVL(BD.DIEN_TICH,0) ELSE DE_O END) DE_O,
(CASE WHEN NVL(BD.DIEN_TICH,0) < NVL(SD_KHAC,0) THEN NVL(BD.DIEN_TICH,0) ELSE SD_KHAC END) SD_KHAC
FROM ( SELECT MA_TAI_SAN,
      SUM(CASE LOAI_BIEN_DONG WHEN '1' THEN 1 WHEN '5' THEN -1 ELSE 0 END) SO_LUONG,
      SUM(CASE WHEN LOAI_BIEN_DONG IN ('1','2') THEN NVL(DIEN_TICH, 0)
               WHEN LOAI_BIEN_DONG IN ('3','5','6') THEN -NVL(DIEN_TICH, 0) END) DIEN_TICH,
      SUM(CASE WHEN LOAI_BIEN_DONG IN ('1','2') THEN NVL(NGUYEN_GIA_NS, 0)
               WHEN LOAI_BIEN_DONG IN ('3','5','6') THEN -NVL(NGUYEN_GIA_NS, 0) END) NGUYEN_GIA_NS,
      SUM(CASE WHEN LOAI_BIEN_DONG IN ('1','2') THEN NVL(NGUYEN_GIA_KHAC, 0)
               WHEN LOAI_BIEN_DONG IN ('3','5','6') THEN -NVL(NGUYEN_GIA_KHAC, 0) END) NGUYEN_GIA_KHAC,
      SUM(CASE WHEN LOAI_BIEN_DONG IN ('1','2') THEN NVL(NGUYEN_GIA_ODA, 0)
               WHEN LOAI_BIEN_DONG IN ('3','5','6') THEN -NVL(NGUYEN_GIA_ODA, 0) END) NGUYEN_GIA_ODA,
      SUM(CASE WHEN LOAI_BIEN_DONG IN ('1','2') THEN NVL(NGUYEN_GIA_VIEN_TRO, 0)
               WHEN LOAI_BIEN_DONG IN ('3','5','6') THEN -NVL(NGUYEN_GIA_VIEN_TRO, 0) END) NGUYEN_GIA_VIEN_TRO 
FROM BD_TAI_SAN BD_TAI_SAN_VIEW
WHERE NGAY_BIEN_DONG <= TO_DATE('31/12/2014','DD/MM/YYYY') AND MA_PHAN_CAP LIKE '%'
GROUP BY MA_TAI_SAN) BD
LEFT JOIN (
        SELECT MA_TAI_SAN,
        LAM_TRU_SO_LV LAM_TRU_SO_NN,
        HD_SN,
        SX_KDDV,
        CHO_THUE,
        SX_KDDV_SAIPHEP,
        DE_O,
        SD_KHAC
    FROM  BD_TAI_SAN
        WHERE BD_ID=(SELECT MAX(BD_ID)
                                FROM BD_TAI_SAN BD
                                WHERE BD.NGAY_BIEN_DONG <= TO_DATE('31/12/2014','DD/MM/YYYY')
                                AND BD_TAI_SAN.MA_TAI_SAN=BD.MA_TAI_SAN
                    )
    ) BD_TAI_SAN_VIEW1 ON BD_TAI_SAN_VIEW1.MA_TAI_SAN=BD.MA_TAI_SAN

JOIN TS_TAI_SAN TS ON TS.MA_TAI_SAN = BD.MA_TAI_SAN  JOIN (SELECT MA_PHAN_CAP MA_PHAN_CAP_DON_VI,
  MA_DON_VI,
  TRANG_THAI_THAY_DOI,
  TEN_DON_VI,
  DM_DONVI.CAP,
  NULL AS MA_SO,
  NULL AS TEN,
  NULL MA_DON_VI_TEMP
FROM DM_DONVI
WHERE 1 = 1  AND DM_DONVI.TRANG_THAI_THAY_DOI = '0' ) DM_DONVI ON DM_DONVI.MA_DON_VI = TS.MA_DON_VI
JOIN (SELECT LOAI_TAI_SAN_ID,MA_PHAN_CAP MA_PHAN_CAP_LOAI_TS,
MA_LOAI_TAI_SAN,
NULL AS MA_SO,
NULL AS TEN
FROM DM_LOAITAISAN WHERE 1=1 ) DM_LOAITAISAN ON DM_LOAITAISAN.LOAI_TAI_SAN_ID = TS.LOAI_TAI_SAN_ID  
WHERE NVL(SO_LUONG,0) > 0 AND BD.MA_TAI_SAN NOT IN (SELECT MA_TAI_SAN FROM KT_TAISAN_31122014) AND (((DM_LOAITAISAN.MA_LOAI_TAI_SAN LIKE '1%' OR DM_LOAITAISAN.MA_LOAI_TAI_SAN LIKE '2%') AND  NVL(DIEN_TICH,0) >= 0) OR (DM_LOAITAISAN.MA_LOAI_TAI_SAN NOT LIKE '1%' AND DM_LOAITAISAN.MA_LOAI_TAI_SAN NOT LIKE '2%') );
COMMIT;


