//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.Web.Reports.CCDC {
    
    public partial class CCDC_GiamOrTang : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "GS.Web.Reports.CCDC.CCDC_GiamOrTang.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");
            this.tableCell3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell3");
            this.tableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell4");
            this.tableCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell5");
            this.tableCell6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell6");
            this.tableCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell7");
            this.tableCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell8");
            this.ngayANDbophan = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ngayANDbophan");
            this.LeftHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("LeftHeader");
            this.CenterHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("CenterHeader");
            this.TenNguoiLapBieu = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenNguoiLapBieu");
            this.lb_GhiChuNLB = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuNLB");
            this.ChucDanhNguoiLapBieu = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhNguoiLapBieu");
            this.lb_GhiChuKeToan = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuKeToan");
            this.ChucDanhKeToanTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhKeToanTruong");
            this.TenKeToanTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenKeToanTruong");
            this.TenThuTruongDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenThuTruongDonVi");
            this.lb_GhiChuThuTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuThuTruong");
            this.ChucDanhThuTruongDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhThuTruongDonVi");
            this.DiaDanhBaoCao = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("DiaDanhBaoCao");
            this.label8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label8");
            this.table5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table5");
            this.tableRow5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow5");
            this.tableCell29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell29");
            this.tableCell30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell30");
            this.tableCell31 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell31");
            this.tableCell32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell32");
            this.chuthich = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("chuthich");
            this.table4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table4");
            this.tableRow4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow4");
            this.tableCell21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell21");
            this.tableCell22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell22");
            this.tableCell23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell23");
            this.tableCell24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell24");
            this.tableCell25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell25");
            this.tableCell26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell26");
            this.tableCell27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell27");
            this.tableCell28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell28");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.lblDatetimeCreate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblDatetimeCreate");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell3;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell5;
        private DevExpress.XtraReports.UI.XRTableCell tableCell6;
        private DevExpress.XtraReports.UI.XRTableCell tableCell7;
        private DevExpress.XtraReports.UI.XRTableCell tableCell8;
        private DevExpress.XtraReports.UI.XRLabel ngayANDbophan;
        private DevExpress.XtraReports.UI.XRLabel LeftHeader;
        private DevExpress.XtraReports.UI.XRLabel CenterHeader;
        private DevExpress.XtraReports.UI.XRLabel TenNguoiLapBieu;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuNLB;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhNguoiLapBieu;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuKeToan;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhKeToanTruong;
        private DevExpress.XtraReports.UI.XRLabel TenKeToanTruong;
        private DevExpress.XtraReports.UI.XRLabel TenThuTruongDonVi;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuThuTruong;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhThuTruongDonVi;
        private DevExpress.XtraReports.UI.XRLabel DiaDanhBaoCao;
        private DevExpress.XtraReports.UI.XRLabel label8;
        private DevExpress.XtraReports.UI.XRTable table5;
        private DevExpress.XtraReports.UI.XRTableRow tableRow5;
        private DevExpress.XtraReports.UI.XRTableCell tableCell29;
        private DevExpress.XtraReports.UI.XRTableCell tableCell30;
        private DevExpress.XtraReports.UI.XRTableCell tableCell31;
        private DevExpress.XtraReports.UI.XRTableCell tableCell32;
        private DevExpress.XtraReports.UI.XRLabel chuthich;
        private DevExpress.XtraReports.UI.XRTable table4;
        private DevExpress.XtraReports.UI.XRTableRow tableRow4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell21;
        private DevExpress.XtraReports.UI.XRTableCell tableCell22;
        private DevExpress.XtraReports.UI.XRTableCell tableCell23;
        private DevExpress.XtraReports.UI.XRTableCell tableCell24;
        private DevExpress.XtraReports.UI.XRTableCell tableCell25;
        private DevExpress.XtraReports.UI.XRTableCell tableCell26;
        private DevExpress.XtraReports.UI.XRTableCell tableCell27;
        private DevExpress.XtraReports.UI.XRTableCell tableCell28;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRLabel lblDatetimeCreate;
    }
}
