SELECT 
    BD.TAI_SAN_ID,
    BD.DON_VI_ID,
    DONVI.DB_ID AS DB_DON_VI_ID,
    DONVI.TEN AS TEN_DON_VI,
    BD.LOAI_TAI_SAN_ID,
    LOAITAISAN.DB_ID AS DB_LOAI_TAI_SAN_ID,
    BD.LOAI_TAI_SAN_DON_VI_ID,
    BD.LOAI_HINH_TAI_SAN_ID,
    TS.TEN AS TEN_TAI_SAN,
    TS.MA AS MA_TAI_SAN,
    BD.NGUYEN_GIA,
    BD.CHUNG_TU_SO,
    BD.CHUNG_TU_NGAY,
    BD.NGAY_BIEN_DONG,
    BD.NGAY_SU_DUNG,
    TS.DU_AN_ID,
    DA.DB_ID AS DB_DU_AN_ID,
    BD.DON_VI_BO_PHAN_ID,
    DVBP.DB_ID AS DB_DON_VI_BO_PHAN_ID,
    BD.LOAI_BIEN_DONG_ID,
    LYDO.MA AS LY_DO_BIEN_DONG_MA,
    LYDO.DB_ID AS DB_LY_DO_BIEN_DONG_ID,
    BD.LY_DO_BIEN_DONG_ID,
    LYDO.TEN AS TEN_LY_DO,
    BD.NGAY_TAO,
    BD.ID_DB,
    BD.GUID,
    BD.GHI_CHU,
    BD.QUYET_DINH_NGAY,
    BD.NGAY_DUYET,
    (SELECT TEN_DAY_DU FROM QL_NGUOI_DUNG WHERE ID = BD.NGUOI_DUYET_ID) AS NGUOI_DUYET,
    BD.QUYET_DINH_SO,
    --BienDongChiTiet
    BDCT.HINH_THUC_MUA_SAM_MA,
    BDCT.HINH_THUC_MUA_SAM_DB_ID,
    BDCT.HINH_THUC_MUA_SAM_TEN,
    BDCT.MUC_DICH_SU_DUNG_MA,
    BDCT.DB_MUC_DICH_SU_DUNG_ID,
    BDCT.MUC_DICH_SU_DUNG_ID,
    BDCT.NHAN_HIEU,
    BDCT.SO_HIEU,
    BDCT.DIA_BAN_MA,
    BDCT.DB_DIA_BAN_ID,
    BDCT.DIA_BAN_ID,
    BDCT.DB_QUOC_GIA_ID,
    BDCT.DIA_CHI,
    BDCT.DAT_TONG_DIEN_TICH,
    JSON_VALUE(BDCT.DATA_JSON, '$.DAT_GIA_TRI_QUYEN_SD_DAT' RETURNING NUMBER) AS DAT_GIA_TRI_QUYEN_SD_DAT,
    BDCT.HM_SO_NAM_CON_LAI,
    BDCT.HM_TY_LE_HAO_MON,
    BDCT.HM_LUY_KE,
    BDCT.HM_GIA_TRI_CON_LAI,
    BDCT.KH_NGAY_BAT_DAU,
    BDCT.KH_THANG_CON_LAI,
    BDCT.KH_GIA_TINH_KHAU_HAO,
    BDCT.KH_GIA_TRI_TRICH_THANG,
    BDCT.KH_LUY_KE,
    BDCT.KH_CON_LAI,
    BDCT.NHA_SO_TANG,
    BDCT.NHA_NAM_XAY_DUNG,
    BDCT.NHA_DIEN_TICH_XD,
    BDCT.NHA_TONG_DIEN_TICH_XD,
    BDCT.VKT_DIEN_TICH,
    BDCT.VKT_THE_TICH,
    BDCT.VKT_CHIEU_DAI,
    BDCT.OTO_BIEN_KIEM_SOAT,
    BDCT.OTO_SO_CHO_NGOI,
    BDCT.OTO_CHUC_DANH_ID,
    BDCT.OTO_CHUC_DANH_DB_ID,
    BDCT.OTO_CHUC_DANH_TEN,
    BDCT.OTO_CHUC_DANH_MA,
    BDCT.OTO_NHAN_XE_MA,
    BDCT.OTO_NHAN_XE_TEN,
    BDCT.OTO_NHAN_XE_DB_ID,
    BDCT.OTO_NHAN_XE_ID,
    BDCT.OTO_TAI_TRONG,
    BDCT.OTO_CONG_XUAT,
    BDCT.OTO_XI_LANH,
    BDCT.OTO_SO_KHUNG,
    BDCT.OTO_SO_MAY,
    BDCT.THONG_SO_KY_THUAT,
    BDCT.CLN_SO_NAM,
    BDCT.DON_VI_NHAN_DIEU_CHUYEN_MA,
    BDCT.HINH_THUC_XU_LY_MA,
    BDCT.IS_BAN_THANH_LY,
    BDCT.HINH_THUC_XU_LY_ID,
    BDCT.PHI_THU,
    BDCT.PHI_BU_DAP,
    BDCT.PHI_NOP_NGAN_SACH,
    --HỒ SƠ GIẤY TỜ
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_BIEN_BAN_NGHIEM_THU' RETURNING VARCHAR2(50)) AS HS_BIEN_BAN_NGHIEM_THU,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_BIEN_BAN_NGHIEM_THU_NGAY' RETURNING DATE) AS HS_BIEN_BAN_NGHIEM_THU_NGAY,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_CNQSD_SO' RETURNING VARCHAR2(50)) AS HS_CNQSD_SO,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_CNQSD_NGAY' RETURNING DATE) AS HS_CNQSD_NGAY,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_PHAP_LY_KHAC' RETURNING VARCHAR2(50)) AS HS_PHAP_LY_KHAC,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_PHAP_LY_KHAC_NGAY' RETURNING DATE) AS HS_PHAP_LY_KHAC_NGAY,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_BAN_GIAO' RETURNING VARCHAR2(50)) AS HS_QUYET_DINH_BAN_GIAO,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_BAN_GIAO_NGAY' RETURNING DATE) AS HS_QUYET_DINH_BAN_GIAO_NGAY,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_CHO_THUE_SO' RETURNING VARCHAR2(50)) AS HS_QUYET_DINH_CHO_THUE_SO,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_CHO_THUE_NGAY' RETURNING DATE) AS HS_QUYET_DINH_CHO_THUE_NGAY,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_GIAO_SO' RETURNING VARCHAR2(50)) AS HS_QUYET_DINH_GIAO_SO,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_GIAO_NGAY' RETURNING DATE) AS HS_QUYET_DINH_GIAO_NGAY,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_HOP_DONG_CHO_THUE_SO' RETURNING VARCHAR2(50)) AS HS_HOP_DONG_CHO_THUE_SO,
    JSON_VALUE(BDCT.DATA_JSON, '$.HS_HOP_DONG_CHO_THUE_NGAY' RETURNING DATE) AS HS_HOP_DONG_CHO_THUE_NGAY

FROM BD_BIEN_DONG BD
LEFT JOIN TS_TAI_SAN TS ON BD.TAI_SAN_ID = TS.ID
LEFT JOIN DM_LOAI_TAI_SAN LOAITAISAN ON BD.LOAI_TAI_SAN_ID = LOAITAISAN.ID
LEFT JOIN (
            SELECT 
                CT.*,
                HTMS.MA AS HINH_THUC_MUA_SAM_MA,
                HTMS.DB_ID AS HINH_THUC_MUA_SAM_DB_ID,
                HTMS.TEN AS HINH_THUC_MUA_SAM_TEN,
                DVDC.MA AS DON_VI_NHAN_DIEU_CHUYEN_MA,
                HTXL.MA AS HINH_THUC_XU_LY_MA,
                MDSD.MA AS MUC_DICH_SU_DUNG_MA,
                MDSD.DB_ID DB_MUC_DICH_SU_DUNG_ID,
                DIABAN.MA AS DIA_BAN_MA,
                DIABAN.DB_ID AS DB_DIA_BAN_ID,
                CHUCDANH.DB_ID AS OTO_CHUC_DANH_DB_ID,
                CHUCDANH.TEN_CHUC_DANH AS OTO_CHUC_DANH_TEN,
                CHUCDANH.MA_CHUC_DANH AS OTO_CHUC_DANH_MA,
                NHANXE.MA AS OTO_NHAN_XE_MA,
                NHANXE.TEN AS OTO_NHAN_XE_TEN,
                NHANXE.DB_ID AS OTO_NHAN_XE_DB_ID,
                QUOCGIA.DB_ID AS DB_QUOC_GIA_ID
            FROM BD_BIEN_DONG_CHI_TIET CT
            LEFT JOIN DM_DON_VI DVDC ON DVDC.ID = CT.DON_VI_NHAN_DIEU_CHUYEN_ID
            LEFT JOIN DM_HINH_THUC_MUA_SAM HTMS ON HTMS.ID = CT.HINH_THUC_MUA_SAM_ID
            LEFT JOIN DM_HINH_THUC_XU_LY HTXL ON HTXL.ID = CT.HINH_THUC_XU_LY_ID
            LEFT JOIN DM_MUC_DICH_SU_DUNG MDSD ON MDSD.ID = CT.MUC_DICH_SU_DUNG_ID
            LEFT JOIN DM_DIA_BAN DIABAN ON DIABAN.ID = CT.DIA_BAN_ID
            LEFT JOIN DM_CHUC_DANH CHUCDANH ON CHUCDANH.ID = CT.OTO_CHUC_DANH_ID
            LEFT JOIN DM_NHAN_XE NHANXE ON NHANXE.ID = CT.OTO_NHAN_XE_ID
            LEFT JOIN DM_QUOC_GIA QUOCGIA ON QUOCGIA.ID = DIABAN.QUOC_GIA_ID) BDCT
            ON BD.ID = BDCT.BIEN_DONG_ID
LEFT JOIN DM_DON_VI DONVI ON BD.DON_VI_ID = DONVI.ID
LEFT JOIN DM_DU_AN DA ON TS.DU_AN_ID = DA.ID
LEFT JOIN DM_DON_VI_BO_PHAN DVBP ON BD.DON_VI_BO_PHAN_ID = DVBP.ID
LEFT JOIN DM_LY_DO_BIEN_DONG LYDO ON LYDO.ID = BD.LY_DO_BIEN_DONG_ID
WHERE BD.ID = 32;







        #region tài sản

        public Decimal? HM_TY_LE_TAI_SAN,
        public Decimal? NUOC_SAN_XUAT_ID,
        public int NAM_SAN_XUAT,
        public Decimal? MIEN_THUE_SO_TIEN,
        public string NUOC_SAN_XUAT,
        public string MA_TAI_SAN_DB,
        public string NGAY_NHAP_TAI_SAN,
        #region TS_NHA
        public Decimal? TS_NHA_DIEN_TICH_XAY_DUNG,
        public string TS_NHA_TAI_SAN_DAT_MA,
        #endregion
        #region TS_OTO
        public Decimal? TS_OTO_DUNG_TICH,
        public String TS_OTO_SO_KHUNG,
        public String TS_OTO_SO_MAY,
        public String TS_OTO_CHUC_DANH_TEN,
        public Decimal? TS_OTO_SO_CAU,
        public string TS_OTO_GCN_DANG_KY,
        public string TS_OTO_CO_QUAN_CAP_DANG_KY,
        #endregion
        #region TS_VKT
        public Decimal? TS_VKT_DIEN_TICH,
        public Decimal? TS_VKT_THE_TICH,
        public Decimal? TS_VKT_CHIEU_DAI,
        #endregion
        #region TS_MAY_MOC
        public string TS_THONG_SO_KY_THUAT,
        #endregion
        #region TS_CLN
        public int? TS_CLN_NAM_SINH,
        #endregion
        #endregion
        #region biến động
        
        #endregion
        #region Hiện trạng sử dụng
        public List<TaiSanHienTrangSuDungDBModel> LST_HIEN_TRANG,
        public string LST_HIEN_TRANG_JSON,
        #endregion
        #region Nguồn vốn
        public decimal? NV_NGAN_SACH,
        public decimal? NV_HDSN,
        public decimal? NV_NGUON_KHAC,
        public decimal? NV_VIEN_TRO,
        #endregion
        
        #endregion
    }