CREATE OR REPLACE PROCEDURE GET_INFO_DONG_BO_BIEN_DONG 
(
  P_BIEN_DONG_ID IN NUMBER 
, P_OUT OUT SYS_REFCURSOR 
) AS 
BEGIN
  OPEN P_OUT FOR 
  SELECT 
        BD.TAI_SAN_ID,
        BD.DON_VI_ID,
        DONVI.DB_ID AS DB_DON_VI_ID,
        DONVI.TEN AS TEN_DON_VI,
        BD.LOAI_TAI_SAN_ID,
        LOAITAISAN.DB_ID AS DB_LOAI_TAI_SAN_ID,
        BD.LOAI_TAI_SAN_DON_VI_ID,
        BD.LOAI_HINH_TAI_SAN_ID,
        BD.NGUYEN_GIA,
        BD.CHUNG_TU_SO,
        TO_CHAR(BD.CHUNG_TU_NGAY,'dd-MM-yyyy') AS CHUNG_TU_NGAY,
        TO_CHAR(BD.NGAY_BIEN_DONG,'dd-MM-yyyy') AS NGAY_BIEN_DONG,
        TO_CHAR(BD.NGAY_SU_DUNG,'dd-MM-yyyy') AS NGAY_SU_DUNG,
        BD.DON_VI_BO_PHAN_ID,
        DVBP.DB_ID AS DB_DON_VI_BO_PHAN_ID,
        BD.LOAI_BIEN_DONG_ID,
        LYDO.MA AS LY_DO_BIEN_DONG_MA,
        LYDO.DB_ID AS DB_LY_DO_BIEN_DONG_ID,
        BD.LY_DO_BIEN_DONG_ID,
        LYDO.TEN AS TEN_LY_DO,
        TO_CHAR(BD.NGAY_TAO,'dd-MM-yyyy') AS NGAY_TAO,
        BD.ID_DB,
        BD.GUID,
        BD.GHI_CHU,
        TO_CHAR(BD.QUYET_DINH_NGAY,'dd-MM-yyyy') AS QUYET_DINH_NGAY,
        TO_CHAR(BD.NGAY_DUYET,'dd-MM-yyyy') AS NGAY_DUYET,
        (SELECT TEN_DAY_DU FROM QL_NGUOI_DUNG WHERE ID = BD.NGUOI_DUYET_ID) AS NGUOI_DUYET,
        BD.QUYET_DINH_SO,
        --BienDongChiTiet
        BDCT.HINH_THUC_MUA_SAM_MA,
        BDCT.HINH_THUC_MUA_SAM_DB_ID,
        BDCT.HINH_THUC_MUA_SAM_TEN,
        BDCT.MUC_DICH_SU_DUNG_MA,
        BDCT.DB_MUC_DICH_SU_DUNG_ID,
        BDCT.MUC_DICH_SU_DUNG_ID,
        BDCT.NHAN_HIEU,
        BDCT.SO_HIEU,
        BDCT.DIA_BAN_MA,
        BDCT.DB_DIA_BAN_ID,
        BDCT.DIA_BAN_ID,
        BDCT.DB_QUOC_GIA_ID,
        BDCT.DIA_CHI,
        BDCT.DAT_TONG_DIEN_TICH,
        JSON_VALUE(BDCT.DATA_JSON, '$.DAT_GIA_TRI_QUYEN_SD_DAT' RETURNING NUMBER) AS DAT_GIA_TRI_QUYEN_SD_DAT,
        BDCT.HM_SO_NAM_CON_LAI,
        BDCT.HM_TY_LE_HAO_MON,
        BDCT.HM_LUY_KE,
        BDCT.HM_GIA_TRI_CON_LAI,
        TO_CHAR(BDCT.KH_NGAY_BAT_DAU,'dd-MM-yyyy') AS KH_NGAY_BAT_DAU,
        BDCT.KH_THANG_CON_LAI,
        BDCT.KH_GIA_TINH_KHAU_HAO,
        BDCT.KH_GIA_TRI_TRICH_THANG,
        BDCT.KH_LUY_KE,
        BDCT.KH_CON_LAI,
        BDCT.NHA_SO_TANG,
        BDCT.NHA_NAM_XAY_DUNG,
        BDCT.NHA_DIEN_TICH_XD,
        BDCT.NHA_TONG_DIEN_TICH_XD,
        BDCT.VKT_DIEN_TICH,
        BDCT.VKT_THE_TICH,
        BDCT.VKT_CHIEU_DAI,
        BDCT.OTO_BIEN_KIEM_SOAT,
        BDCT.OTO_SO_CHO_NGOI,
        BDCT.OTO_CHUC_DANH_ID,
        BDCT.OTO_CHUC_DANH_DB_ID,
        BDCT.OTO_CHUC_DANH_TEN,
        BDCT.OTO_CHUC_DANH_MA,
        BDCT.OTO_NHAN_XE_MA,
        BDCT.OTO_NHAN_XE_TEN,
        BDCT.OTO_NHAN_XE_DB_ID,
        BDCT.OTO_NHAN_XE_ID,
        BDCT.OTO_TAI_TRONG,
        BDCT.OTO_CONG_XUAT,
        BDCT.OTO_XI_LANH,
        BDCT.OTO_SO_KHUNG,
        BDCT.OTO_SO_MAY,
        BDCT.THONG_SO_KY_THUAT,
        BDCT.CLN_SO_NAM,
        BDCT.DON_VI_NHAN_DIEU_CHUYEN_MA,
        BDCT.HINH_THUC_XU_LY_MA,
        BDCT.IS_BAN_THANH_LY,
        BDCT.HINH_THUC_XU_LY_ID,
        BDCT.PHI_THU,
        BDCT.PHI_BU_DAP,
        BDCT.PHI_NOP_NGAN_SACH,
        --HỒ SƠ GIẤY TỜ
        JSON_VALUE(BDCT.DATA_JSON, '$.HS_BIEN_BAN_NGHIEM_THU' RETURNING VARCHAR2(50)) AS HS_BIEN_BAN_NGHIEM_THU,
        TO_CHAR(JSON_VALUE(BDCT.DATA_JSON, '$.HS_BIEN_BAN_NGHIEM_THU_NGAY' RETURNING DATE),'dd-MM-yyyy') AS HS_BIEN_BAN_NGHIEM_THU_NGAY,
        JSON_VALUE(BDCT.DATA_JSON, '$.HS_CNQSD_SO' RETURNING VARCHAR2(50)) AS HS_CNQSD_SO,
        TO_CHAR(JSON_VALUE(BDCT.DATA_JSON, '$.HS_CNQSD_NGAY' RETURNING DATE),'dd-MM-yyyy') AS HS_CNQSD_NGAY,
        JSON_VALUE(BDCT.DATA_JSON, '$.HS_PHAP_LY_KHAC' RETURNING VARCHAR2(50)) AS HS_PHAP_LY_KHAC,
        TO_CHAR(JSON_VALUE(BDCT.DATA_JSON, '$.HS_PHAP_LY_KHAC_NGAY' RETURNING DATE),'dd-MM-yyyy') AS HS_PHAP_LY_KHAC_NGAY,
        JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_BAN_GIAO' RETURNING VARCHAR2(50)) AS HS_QUYET_DINH_BAN_GIAO,
        TO_CHAR(JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_BAN_GIAO_NGAY' RETURNING DATE),'dd-MM-yyyy') AS HS_QUYET_DINH_BAN_GIAO_NGAY,
        JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_CHO_THUE_SO' RETURNING VARCHAR2(50)) AS HS_QUYET_DINH_CHO_THUE_SO,
        TO_CHAR(JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_CHO_THUE_NGAY' RETURNING DATE),'dd-MM-yyyy') AS HS_QUYET_DINH_CHO_THUE_NGAY,
        JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_GIAO_SO' RETURNING VARCHAR2(50)) AS HS_QUYET_DINH_GIAO_SO,
        TO_CHAR(JSON_VALUE(BDCT.DATA_JSON, '$.HS_QUYET_DINH_GIAO_NGAY' RETURNING DATE),'dd-MM-yyyy') AS HS_QUYET_DINH_GIAO_NGAY,
        JSON_VALUE(BDCT.DATA_JSON, '$.HS_HOP_DONG_CHO_THUE_SO' RETURNING VARCHAR2(50)) AS HS_HOP_DONG_CHO_THUE_SO,
        TO_CHAR(JSON_VALUE(BDCT.DATA_JSON, '$.HS_HOP_DONG_CHO_THUE_NGAY' RETURNING DATE),'dd-MM-yyyy') AS HS_HOP_DONG_CHO_THUE_NGAY,
        -- TÀI SẢN 
        TAISAN.TEN_TAI_SAN,
        TAISAN.MA_TAI_SAN,
        TAISAN.DU_AN_ID,
        TAISAN.DB_DU_AN_ID,
        TAISAN.HM_TY_LE_TAI_SAN,
        TAISAN.NUOC_SAN_XUAT_ID,
        TAISAN.NAM_SAN_XUAT,
        TAISAN.MIEN_THUE_SO_TIEN,
        TAISAN.NUOC_SAN_XUAT,
        TAISAN.MA_TAI_SAN_DB,
        TAISAN.NGAY_NHAP_TAI_SAN,
        -- TS_NHA
        TAISAN.TS_NHA_DIEN_TICH_XAY_DUNG,
        TAISAN.TS_NHA_TAI_SAN_DAT_MA,
        -- TS_OTO
        TAISAN.TS_OTO_DUNG_TICH,
        TAISAN.TS_OTO_SO_KHUNG,
        TAISAN.TS_OTO_SO_MAY,
        TAISAN.TS_OTO_CHUC_DANH_TEN,
        TAISAN.TS_OTO_SO_CAU,
        TAISAN.TS_OTO_GCN_DANG_KY,
        TAISAN.TS_OTO_CO_QUAN_CAP_DANG_KY,
        -- TS_VKT
        TAISAN.TS_VKT_DIEN_TICH,
        TAISAN.TS_VKT_THE_TICH,
        TAISAN.TS_VKT_CHIEU_DAI,
        TAISAN.TS_THONG_SO_KY_THUAT,
        -- TS_CLN
        TAISAN.TS_CLN_NAM_SINH,
        (SELECT '['||(LISTAGG('{"HIEN_TRANG_ID":'||HIEN_TRANG_ID||',"GIA_TRI_NUMBER":'||NVL(GIA_TRI_NUMBER,0)||',"GIA_TRI_CHECKBOX":'||(CASE WHEN GIA_TRI_CHECKBOX IS NULL THEN 'null' ELSE TO_CHAR(GIA_TRI_CHECKBOX) END)||'}', ',') WITHIN GROUP (ORDER BY 1))||']' AS LST_HIEN_TRANG_JSON 
            FROM TS_TAI_SAN_HIEN_TRANG_SU_DUNG
            WHERE BIEN_DONG_ID = BD.ID) AS LST_HIEN_TRANG_JSON,
        -- NGUỒN VỐN
        NGUON_VON.NV_NGAN_SACH,
        NGUON_VON.NV_HDSN,
        NGUON_VON.NV_NGUON_KHAC,
        NGUON_VON.NV_VIEN_TRO
    FROM BD_BIEN_DONG BD
        LEFT JOIN (
                    SELECT 
                        TS.ID,
                        TS.TEN AS TEN_TAI_SAN,
                        TS.MA AS MA_TAI_SAN,
                        TS.DU_AN_ID,
                        DA.DB_ID AS DB_DU_AN_ID,
                        TS.HM_TY_LE AS HM_TY_LE_TAI_SAN,
                        TS.NUOC_SAN_XUAT_ID,
                        TS.NAM_SAN_XUAT,
                        TS.MIEN_THUE_SO_TIEN,
                        (SELECT TEN FROM DM_QUOC_GIA WHERE ID = TS.NUOC_SAN_XUAT_ID) AS NUOC_SAN_XUAT,
                        TS.MA_DB MA_TAI_SAN_DB,
                        TO_CHAR(TS.NGAY_NHAP,'dd-MM-yyyy') AS NGAY_NHAP_TAI_SAN,
                        -- TS_NHA
                        TSNHA.DIEN_TICH_XAY_DUNG AS TS_NHA_DIEN_TICH_XAY_DUNG,
                        (CASE   WHEN TSNHA.TAI_SAN_DAT_ID IS NOT NULL THEN
                                    (SELECT MA FROM TS_TAI_SAN WHERE ID = TSNHA.TAI_SAN_DAT_ID)
                                ELSE NULL END) TS_NHA_TAI_SAN_DAT_MA,
                        
                        -- TS_OTO
                        TSOTO.DUNG_TICH AS TS_OTO_DUNG_TICH,
                        TSOTO.SO_KHUNG AS TS_OTO_SO_KHUNG,
                        TSOTO.SO_MAY AS TS_OTO_SO_MAY,
                        (CASE   WHEN TSOTO.CHUC_DANH_ID IS NOT NULL THEN
                                    (SELECT TEN_CHUC_DANH FROM DM_CHUC_DANH WHERE ID = TSOTO.CHUC_DANH_ID)
                                ELSE NULL END) AS TS_OTO_CHUC_DANH_TEN,
                        TSOTO.SO_CAU_XE AS TS_OTO_SO_CAU,
                        TSOTO.GCN_DANG_KY AS TS_OTO_GCN_DANG_KY,
                        TSOTO.CO_QUAN_CAP_DANG_KY AS TS_OTO_CO_QUAN_CAP_DANG_KY,
                        
                        -- TS_VKT
                        TSVKT.DIEN_TICH AS TS_VKT_DIEN_TICH,
                        TSVKT.THE_TICH AS TS_VKT_THE_TICH,
                        TSVKT.CHIEU_DAI AS TS_VKT_CHIEU_DAI,
                        (CASE
                            WHEN TS.LOAI_HINH_TAI_SAN_ID = 9 THEN
                                TSVOHINH.THONG_SO_KY_THUAT
                            ELSE TSMAYMOC.THONG_SO_KY_THUAT END
                            ) AS TS_THONG_SO_KY_THUAT,
                        -- TS_CLN
                        TSCLN.NAM_SINH AS TS_CLN_NAM_SINH
                        
                    FROM TS_TAI_SAN TS
                    LEFT JOIN DM_DU_AN DA ON TS.DU_AN_ID = DA.ID
                    -- LEFT JOIN TS_TAI_SAN_DAT TSDAT ON TS.ID = TSDAT.TAI_SAN_ID
                    LEFT JOIN TS_TAI_SAN_NHA TSNHA ON TS.ID = TSNHA.TAI_SAN_ID
                    LEFT JOIN TS_TAI_SAN_OTO TSOTO ON TS.ID = TSOTO.TAI_SAN_ID
                    LEFT JOIN TS_TAI_SAN_CLN TSCLN ON TS.ID = TSCLN.TAI_SAN_ID
                    LEFT JOIN TS_TAI_SAN_VKT TSVKT ON TS.ID = TSVKT.TAI_SAN_ID
                    LEFT JOIN TS_TAI_SAN_VO_HINH TSVOHINH ON TS.ID = TSVOHINH.TAI_SAN_ID
                    LEFT JOIN TS_TAI_SAN_MAY_MOC TSMAYMOC ON TS.ID = TSMAYMOC.TAI_SAN_ID
                ) TAISAN ON BD.TAI_SAN_ID = TAISAN.ID
        LEFT JOIN (
                    SELECT 
                        CT.*,
                        HTMS.MA AS HINH_THUC_MUA_SAM_MA,
                        HTMS.DB_ID AS HINH_THUC_MUA_SAM_DB_ID,
                        HTMS.TEN AS HINH_THUC_MUA_SAM_TEN,
                        DVDC.MA AS DON_VI_NHAN_DIEU_CHUYEN_MA,
                        HTXL.MA AS HINH_THUC_XU_LY_MA,
                        MDSD.MA AS MUC_DICH_SU_DUNG_MA,
                        MDSD.DB_ID DB_MUC_DICH_SU_DUNG_ID,
                        DIABAN.MA AS DIA_BAN_MA,
                        DIABAN.DB_ID AS DB_DIA_BAN_ID,
                        CHUCDANH.DB_ID AS OTO_CHUC_DANH_DB_ID,
                        CHUCDANH.TEN_CHUC_DANH AS OTO_CHUC_DANH_TEN,
                        CHUCDANH.MA_CHUC_DANH AS OTO_CHUC_DANH_MA,
                        NHANXE.MA AS OTO_NHAN_XE_MA,
                        NHANXE.TEN AS OTO_NHAN_XE_TEN,
                        NHANXE.DB_ID AS OTO_NHAN_XE_DB_ID,
                        QUOCGIA.DB_ID AS DB_QUOC_GIA_ID
                    FROM BD_BIEN_DONG_CHI_TIET CT
                        LEFT JOIN DM_DON_VI DVDC ON DVDC.ID = CT.DON_VI_NHAN_DIEU_CHUYEN_ID
                        LEFT JOIN DM_HINH_THUC_MUA_SAM HTMS ON HTMS.ID = CT.HINH_THUC_MUA_SAM_ID
                        LEFT JOIN DM_HINH_THUC_XU_LY HTXL ON HTXL.ID = CT.HINH_THUC_XU_LY_ID
                        LEFT JOIN DM_MUC_DICH_SU_DUNG MDSD ON MDSD.ID = CT.MUC_DICH_SU_DUNG_ID
                        LEFT JOIN DM_DIA_BAN DIABAN ON DIABAN.ID = CT.DIA_BAN_ID
                        LEFT JOIN DM_CHUC_DANH CHUCDANH ON CHUCDANH.ID = CT.OTO_CHUC_DANH_ID
                        LEFT JOIN DM_NHAN_XE NHANXE ON NHANXE.ID = CT.OTO_NHAN_XE_ID
                        LEFT JOIN DM_QUOC_GIA QUOCGIA ON QUOCGIA.ID = DIABAN.QUOC_GIA_ID
                ) BDCT ON BD.ID = BDCT.BIEN_DONG_ID
        LEFT JOIN (
                    SELECT 
                        BIEN_DONG_ID,
                        SUM(CASE WHEN NGUON_VON_ID = 1 THEN GIA_TRI ELSE 0 END) AS NV_NGAN_SACH,
                        SUM(CASE WHEN NGUON_VON_ID = 2 THEN GIA_TRI ELSE 0 END) AS NV_HDSN,
                        SUM(CASE WHEN NGUON_VON_ID = 3 THEN GIA_TRI ELSE 0 END) AS NV_NGUON_KHAC,
                        SUM(CASE WHEN NGUON_VON_ID = 4 THEN GIA_TRI ELSE 0 END) AS NV_VIEN_TRO
                    FROM TS_TAI_SAN_NGUON_VON
                    GROUP BY BIEN_DONG_ID
                ) NGUON_VON ON BD.ID =  NGUON_VON.BIEN_DONG_ID
        LEFT JOIN DM_DON_VI DONVI ON BD.DON_VI_ID = DONVI.ID
        LEFT JOIN DM_DON_VI_BO_PHAN DVBP ON BD.DON_VI_BO_PHAN_ID = DVBP.ID
        LEFT JOIN DM_LY_DO_BIEN_DONG LYDO ON LYDO.ID = BD.LY_DO_BIEN_DONG_ID
        LEFT JOIN DM_LOAI_TAI_SAN LOAITAISAN ON BD.LOAI_TAI_SAN_ID = LOAITAISAN.ID
    WHERE BD.ID = P_BIEN_DONG_ID;
    CLOSE P_OUT;
    RETURN;
END GET_INFO_DONG_BO_BIEN_DONG;