CREATE OR REPLACE PROCEDURE UPDATE_TREE_NODE_NHOM_CONG_CU AS 
TREE_NODE_PARENT VARCHAR(255);
BEGIN
    FOR RECORD IN (SELECT LEVEL
							,DM.TREE_LEVEL
							,DM.ID
							,DM.PARENT_ID
							,DM.TREE_NODE
							,PRIOR DM.TREE_NODE AS PARENT_TREE_NODE
						FROM DM_NHOM_CONG_CU DM
						CONNECT BY PRIOR DM.ID = DM.PARENT_ID
						START  WITH DM.PARENT_ID IS NULL)
    LOOP
        TREE_NODE_PARENT:=NULL;
        IF RECORD.PARENT_ID IS NOT NULL THEN
            SELECT
                TREE_NODE INTO TREE_NODE_PARENT
            FROM DM_NHOM_CONG_CU
            WHERE ID = RECORD.PARENT_ID;
        END IF;
        UPDATE DM_NHOM_CONG_CU 
        SET TREE_NODE =   (CASE WHEN TREE_NODE_PARENT IS NULL
                                THEN LPAD(ID, 8, '0')
                                ELSE TREE_NODE_PARENT||'-'||LPAD(ID, 8, '0') END),
        TREE_LEVEL = RECORD.LEVEL
        WHERE ID=RECORD.ID;
        COMMIT;
    END LOOP;
END UPDATE_TREE_NODE_NHOM_CONG_CU;