//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.Web.Reports.TS_BCKK {
    
    public partial class rptTS_BCKK_06a_DKTSC_DVSDTS : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "GS.Web.Reports.TS_BCKK.rptTS_BCKK_06a_DKTSC_DVSDTS.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.tableRow3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow3");
            this.tableRow7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow7");
            this.tableRow8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow8");
            this.tableRow9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow9");
            this.tableRow10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow10");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");
            this.cuMQH = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("cuMQH");
            this.moiMQH = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("moiMQH");
            this.tableCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell5");
            this.tableCell6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell6");
            this.tableCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell7");
            this.tableCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell8");
            this.cuTenDV = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("cuTenDV");
            this.moiTenDV = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("moiTenDV");
            this.tableCell11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell11");
            this.tableCell12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell12");
            this.tableCell13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell13");
            this.tableCell20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell20");
            this.cuCoQuanQL = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("cuCoQuanQL");
            this.moiCoQuanQL = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("moiCoQuanQL");
            this.tableCell23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell23");
            this.tableCell24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell24");
            this.tableCell25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell25");
            this.tableCell26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell26");
            this.cuLoaiDV = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("cuLoaiDV");
            this.moiLoaiDV = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("moiLoaiDV");
            this.tableCell29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell29");
            this.tableCell30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell30");
            this.tableCell31 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell31");
            this.tableCell32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell32");
            this.cuKhoiDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("cuKhoiDonVi");
            this.moiKhoiDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("moiKhoiDonVi");
            this.tableCell35 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell35");
            this.tableCell36 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell36");
            this.tableCell37 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell37");
            this.tableCell38 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell38");
            this.cuLoaiHinhDV = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("cuLoaiHinhDV");
            this.moiLoaiHinhDV = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("moiLoaiHinhDV");
            this.tableCell41 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell41");
            this.tableCell42 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell42");
            this.lblDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblDonVi");
            this.label4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label4");
            this.label2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label2");
            this.table3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table3");
            this.tableRow4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow4");
            this.tableCell14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell14");
            this.tableCell15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell15");
            this.tableCell16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell16");
            this.tableCell17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell17");
            this.tableCell18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell18");
            this.tableCell19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell19");
            this.lb_GhiChuThuTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuThuTruong");
            this.label12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label12");
            this.DiaDanhBaoCao = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("DiaDanhBaoCao");
            this.ChucDanhThuTruongDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhThuTruongDonVi");
            this.TenThuTruongDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenThuTruongDonVi");
            this.TenKeToanTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenKeToanTruong");
            this.ChucDanhKeToanTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhKeToanTruong");
            this.ChucDanhNguoiLapBieu = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhNguoiLapBieu");
            this.TenNguoiLapBieu = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenNguoiLapBieu");
            this.lb_GhiChuNLB = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuNLB");
            this.lb_GhiChuKeToan = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuKeToan");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow3;
        private DevExpress.XtraReports.UI.XRTableRow tableRow7;
        private DevExpress.XtraReports.UI.XRTableRow tableRow8;
        private DevExpress.XtraReports.UI.XRTableRow tableRow9;
        private DevExpress.XtraReports.UI.XRTableRow tableRow10;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRTableCell cuMQH;
        private DevExpress.XtraReports.UI.XRTableCell moiMQH;
        private DevExpress.XtraReports.UI.XRTableCell tableCell5;
        private DevExpress.XtraReports.UI.XRTableCell tableCell6;
        private DevExpress.XtraReports.UI.XRTableCell tableCell7;
        private DevExpress.XtraReports.UI.XRTableCell tableCell8;
        private DevExpress.XtraReports.UI.XRTableCell cuTenDV;
        private DevExpress.XtraReports.UI.XRTableCell moiTenDV;
        private DevExpress.XtraReports.UI.XRTableCell tableCell11;
        private DevExpress.XtraReports.UI.XRTableCell tableCell12;
        private DevExpress.XtraReports.UI.XRTableCell tableCell13;
        private DevExpress.XtraReports.UI.XRTableCell tableCell20;
        private DevExpress.XtraReports.UI.XRTableCell cuCoQuanQL;
        private DevExpress.XtraReports.UI.XRTableCell moiCoQuanQL;
        private DevExpress.XtraReports.UI.XRTableCell tableCell23;
        private DevExpress.XtraReports.UI.XRTableCell tableCell24;
        private DevExpress.XtraReports.UI.XRTableCell tableCell25;
        private DevExpress.XtraReports.UI.XRTableCell tableCell26;
        private DevExpress.XtraReports.UI.XRTableCell cuLoaiDV;
        private DevExpress.XtraReports.UI.XRTableCell moiLoaiDV;
        private DevExpress.XtraReports.UI.XRTableCell tableCell29;
        private DevExpress.XtraReports.UI.XRTableCell tableCell30;
        private DevExpress.XtraReports.UI.XRTableCell tableCell31;
        private DevExpress.XtraReports.UI.XRTableCell tableCell32;
        private DevExpress.XtraReports.UI.XRTableCell cuKhoiDonVi;
        private DevExpress.XtraReports.UI.XRTableCell moiKhoiDonVi;
        private DevExpress.XtraReports.UI.XRTableCell tableCell35;
        private DevExpress.XtraReports.UI.XRTableCell tableCell36;
        private DevExpress.XtraReports.UI.XRTableCell tableCell37;
        private DevExpress.XtraReports.UI.XRTableCell tableCell38;
        private DevExpress.XtraReports.UI.XRTableCell cuLoaiHinhDV;
        private DevExpress.XtraReports.UI.XRTableCell moiLoaiHinhDV;
        private DevExpress.XtraReports.UI.XRTableCell tableCell41;
        private DevExpress.XtraReports.UI.XRTableCell tableCell42;
        private DevExpress.XtraReports.UI.XRLabel lblDonVi;
        private DevExpress.XtraReports.UI.XRLabel label4;
        private DevExpress.XtraReports.UI.XRLabel label2;
        private DevExpress.XtraReports.UI.XRTable table3;
        private DevExpress.XtraReports.UI.XRTableRow tableRow4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell14;
        private DevExpress.XtraReports.UI.XRTableCell tableCell15;
        private DevExpress.XtraReports.UI.XRTableCell tableCell16;
        private DevExpress.XtraReports.UI.XRTableCell tableCell17;
        private DevExpress.XtraReports.UI.XRTableCell tableCell18;
        private DevExpress.XtraReports.UI.XRTableCell tableCell19;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuThuTruong;
        private DevExpress.XtraReports.UI.XRLabel label12;
        private DevExpress.XtraReports.UI.XRLabel DiaDanhBaoCao;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhThuTruongDonVi;
        private DevExpress.XtraReports.UI.XRLabel TenThuTruongDonVi;
        private DevExpress.XtraReports.UI.XRLabel TenKeToanTruong;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhKeToanTruong;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhNguoiLapBieu;
        private DevExpress.XtraReports.UI.XRLabel TenNguoiLapBieu;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuNLB;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuKeToan;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
    }
}
