//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.Web.Reports.TS_BCCK {
    
    public partial class rptTS_BCCK_DM_TS_DIEU_CHUYEN_BAN_GIAO : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "GS.Web.Reports.TS_BCCK.rptTS_BCCK_DM_TS_DIEU_CHUYEN_BAN_GIAO.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
            this.table4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table4");
            this.tableRow12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow12");
            this.tableCell13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell13");
            this.tableCell36 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell36");
            this.tableCell44 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell44");
            this.tableCell47 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell47");
            this.tableCell49 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell49");
            this.tableCell50 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell50");
            this.tieuDe = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("tieuDe");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tableRow5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow5");
            this.tableRow6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow6");
            this.lblBoNganhTinh = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblBoNganhTinh");
            this.lblDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblDonVi");
            this.lblMaDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblMaDonVi");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.lb_GhiChuThuTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuThuTruong");
            this.label12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label12");
            this.DiaDanhBaoCao = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("DiaDanhBaoCao");
            this.ChucDanhThuTruongDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhThuTruongDonVi");
            this.TenThuTruongDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenThuTruongDonVi");
            this.TenKeToanTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenKeToanTruong");
            this.ChucDanhKeToanTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhKeToanTruong");
            this.ChucDanhNguoiLapBieu = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhNguoiLapBieu");
            this.TenNguoiLapBieu = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenNguoiLapBieu");
            this.lb_GhiChuNLB = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuNLB");
            this.lb_GhiChuKeToan = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuKeToan");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");
            this.tableCell3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell3");
            this.tableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell4");
            this.tableCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell7");
            this.tableCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell8");
            this.tableCell9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell9");
            this.chuthich = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("chuthich");
            this.table3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table3");
            this.tableRow10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow10");
            this.tableCell102 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell102");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell103 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell103");
            this.tableCell106 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell106");
            this.tableCell110 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell110");
            this.tableCell11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell11");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.lblDatetimeCreate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblDatetimeCreate");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRTable table4;
        private DevExpress.XtraReports.UI.XRTableRow tableRow12;
        private DevExpress.XtraReports.UI.XRTableCell tableCell13;
        private DevExpress.XtraReports.UI.XRTableCell tableCell36;
        private DevExpress.XtraReports.UI.XRTableCell tableCell44;
        private DevExpress.XtraReports.UI.XRTableCell tableCell47;
        private DevExpress.XtraReports.UI.XRTableCell tableCell49;
        private DevExpress.XtraReports.UI.XRTableCell tableCell50;
        private DevExpress.XtraReports.UI.XRLabel tieuDe;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow5;
        private DevExpress.XtraReports.UI.XRTableRow tableRow6;
        private DevExpress.XtraReports.UI.XRTableCell lblBoNganhTinh;
        private DevExpress.XtraReports.UI.XRTableCell lblDonVi;
        private DevExpress.XtraReports.UI.XRTableCell lblMaDonVi;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuThuTruong;
        private DevExpress.XtraReports.UI.XRLabel label12;
        private DevExpress.XtraReports.UI.XRLabel DiaDanhBaoCao;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhThuTruongDonVi;
        private DevExpress.XtraReports.UI.XRLabel TenThuTruongDonVi;
        private DevExpress.XtraReports.UI.XRLabel TenKeToanTruong;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhKeToanTruong;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhNguoiLapBieu;
        private DevExpress.XtraReports.UI.XRLabel TenNguoiLapBieu;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuNLB;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuKeToan;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell3;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell7;
        private DevExpress.XtraReports.UI.XRTableCell tableCell8;
        private DevExpress.XtraReports.UI.XRTableCell tableCell9;
        private DevExpress.XtraReports.UI.XRLabel chuthich;
        private DevExpress.XtraReports.UI.XRTable table3;
        private DevExpress.XtraReports.UI.XRTableRow tableRow10;
        private DevExpress.XtraReports.UI.XRTableCell tableCell102;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell103;
        private DevExpress.XtraReports.UI.XRTableCell tableCell106;
        private DevExpress.XtraReports.UI.XRTableCell tableCell110;
        private DevExpress.XtraReports.UI.XRTableCell tableCell11;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRLabel lblDatetimeCreate;
    }
}
