//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS.Web.Reports.TS_BCCK {
    
    public partial class rptTS_BCCK_M01_KHMS_TS : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "GS.Web.Reports.TS_BCCK.rptTS_BCCK_M01_KHMS_TS.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
            this.table9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table9");
            this.tableRow13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow13");
            this.tableCell100 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell100");
            this.tableCell101 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell101");
            this.tableCell103 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell103");
            this.tableCell104 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell104");
            this.tableCell105 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell105");
            this.tableCell106 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell106");
            this.tableCell107 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell107");
            this.tableCell108 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell108");
            this.tableCell109 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell109");
            this.tableCell110 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell110");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.label2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label2");
            this.label4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label4");
            this.tableRow4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow4");
            this.tableRow5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow5");
            this.tableRow6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow6");
            this.lblBoNganhTinh = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblBoNganhTinh");
            this.lblDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblDonVi");
            this.lblMaDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lblMaDonVi");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");
            this.tableCell3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell3");
            this.tableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell4");
            this.tableCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell5");
            this.tableCell6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell6");
            this.tableCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell7");
            this.tableCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell8");
            this.tableCell9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell9");
            this.tableCell11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell11");
            this.TenThuTruongDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenThuTruongDonVi");
            this.TenKeToanTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenKeToanTruong");
            this.ChucDanhKeToanTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhKeToanTruong");
            this.ChucDanhNguoiLapBieu = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhNguoiLapBieu");
            this.TenNguoiLapBieu = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("TenNguoiLapBieu");
            this.ChucDanhThuTruongDonVi = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("ChucDanhThuTruongDonVi");
            this.label8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label8");
            this.label7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label7");
            this.lblNguon = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblNguon");
            this.lb_GhiChuThuTruong = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuThuTruong");
            this.lb_GhiChuKeToan = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuKeToan");
            this.lb_GhiChuNLB = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lb_GhiChuNLB");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.lblDatetimeCreate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblDatetimeCreate");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRTable table9;
        private DevExpress.XtraReports.UI.XRTableRow tableRow13;
        private DevExpress.XtraReports.UI.XRTableCell tableCell100;
        private DevExpress.XtraReports.UI.XRTableCell tableCell101;
        private DevExpress.XtraReports.UI.XRTableCell tableCell103;
        private DevExpress.XtraReports.UI.XRTableCell tableCell104;
        private DevExpress.XtraReports.UI.XRTableCell tableCell105;
        private DevExpress.XtraReports.UI.XRTableCell tableCell106;
        private DevExpress.XtraReports.UI.XRTableCell tableCell107;
        private DevExpress.XtraReports.UI.XRTableCell tableCell108;
        private DevExpress.XtraReports.UI.XRTableCell tableCell109;
        private DevExpress.XtraReports.UI.XRTableCell tableCell110;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRLabel label2;
        private DevExpress.XtraReports.UI.XRLabel label4;
        private DevExpress.XtraReports.UI.XRTableRow tableRow4;
        private DevExpress.XtraReports.UI.XRTableRow tableRow5;
        private DevExpress.XtraReports.UI.XRTableRow tableRow6;
        private DevExpress.XtraReports.UI.XRTableCell lblBoNganhTinh;
        private DevExpress.XtraReports.UI.XRTableCell lblDonVi;
        private DevExpress.XtraReports.UI.XRTableCell lblMaDonVi;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell3;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell5;
        private DevExpress.XtraReports.UI.XRTableCell tableCell6;
        private DevExpress.XtraReports.UI.XRTableCell tableCell7;
        private DevExpress.XtraReports.UI.XRTableCell tableCell8;
        private DevExpress.XtraReports.UI.XRTableCell tableCell9;
        private DevExpress.XtraReports.UI.XRTableCell tableCell11;
        private DevExpress.XtraReports.UI.XRLabel TenThuTruongDonVi;
        private DevExpress.XtraReports.UI.XRLabel TenKeToanTruong;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhKeToanTruong;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhNguoiLapBieu;
        private DevExpress.XtraReports.UI.XRLabel TenNguoiLapBieu;
        private DevExpress.XtraReports.UI.XRLabel ChucDanhThuTruongDonVi;
        private DevExpress.XtraReports.UI.XRLabel label8;
        private DevExpress.XtraReports.UI.XRLabel label7;
        private DevExpress.XtraReports.UI.XRLabel lblNguon;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuThuTruong;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuKeToan;
        private DevExpress.XtraReports.UI.XRLabel lb_GhiChuNLB;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRLabel lblDatetimeCreate;
    }
}
